### PR TITLE
Fix #485: Crypto 3.2: Prevent replay attacks

### LINKED ISSUE #485: Crypto 3.2: Prevent replay attacks
#### Associated data

Let's define `ASSOCIATED_DATA` as data trasmitted as plaintext and included in MAC calculation. The content of `ASSOCIATED_DATA` (AD) depends on the scope of encryptor and whether data is associated with the request or the response<sup>1</sup>:

| Version | Scope       | Request | Response |
|---------|-------------|---------|----------|
| == 3.2  | APPLICATION | ByteUtils.joinStrings(VERSION, APPLICATION_KEY) | null |
| == 3.2  | ACTIVATION  | ByteUtils.joinStrings(VERSION, APPLICATION_KEY, ACTIVATION_ID) | null |
| < 3.2   | APPLICATION | null | null |
| < 3.2   | ACTIVATION  | null | null |

> Note 1: The response doesn't use AD in this protocol version 

#### Encryption

In [ECIES Encryption](https://developers.wultra.com/components/powerauth-crypto/1.4.x/documentation/End-To-End-Encryption#ecies-encryption), let's keep the existing algorithm up to step 6 and change the next steps:

7. Get current timestamp.
   ```java
   long TIMESTAMP = Time.getTimestamp();
   byte[] TIMESTAMP_BYTES = ByteUtils.encode(TIMESTAMP); // BigEndian encoding
   ```
8. Compute the MAC of encrypted data, include `ASSOCIATED_DATA` and `SHARED_INFO_2`.
   ```java
   byte[] AD = ByteUtils.concat(ASSOCIATED_DATA, ByteUtils.join(NONCE, TIMESTAMP_BYTES, KEY_EPH_PUB));
   byte[] DATA = Bytes.concat(AD, DATA_ENCRYPTED, SHARED_INFO_2);
   byte[] MAC = Mac.hmacSha256(KEY_MAC, DATA);
   ```
9. Prepare ECIES payload.
   ```java
   EciesPayload payload = (DATA_ENCRYPTED, MAC, KEY_EPH_PUB, NONCE, ASSOCIATED_DATA, TIMESTAMP);
   ```

As you can see the encryptor includes internally more data into MAC calculation than ASSOCIATED_DATA.  

#### Decryption

In [ECIES Decryption](https://developers.wultra.com/components/powerauth-crypto/1.4.x/documentation/End-To-End-Encryption#ecies-decryption), change step 4:

4. Validate the MAC value in payload against expected MAC value. Include `ASSOCIATED_DATA` and `SHARED_INFO_2`. If the MAC values are different, terminate the decryption.
   ```java
   byte[] AD;
   if (TIMESTAMP != null) {
       // Protocol 3.2+
       byte[] TIMESTAMP_BYTES = ByteUtils.encode(TIMESTAMP);
       AD = ByteUtils.concat(ASSOCIATED_DATA, ByteUtils.join(NONCE, TIMESTAMP_BYTES, KEY_EPH_PUB));
   } else {
       // Protocol V3.1 and older
       AD = new byte[0];
   }
   byte[] DATA = Bytes.concat(AD, DATA_ENCRYPTED, SHARED_INFO_2);
   byte[] MAC_EXPECTED = Mac.hmacSha256(KEY_MAC, DATA);
   if (MAC_EXPECTED != MAC) {
       throw EciesException("Invalid MAC"); // terminate the validation with an error
   }
   ```

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java [hunk 1]
```diff
@@ -28,6 +28,28 @@ public class EciesCryptogram {
...
+     * Constructor for ECIES cryptogram used in encrypted requests.
+     *
+     * @param ephemeralPublicKey Ephemeral public key.
+     * @param mac MAC computed for key and data.
+     * @param encryptedData Encrypted data.
+     * @param nonce Nonce, required for protocol V3.1+.
+     * @param associatedData Associated data, required for protocol V3.2+.
+     * @param timestamp Timestamp, required for protocol V3.2+.
+     */
+    public EciesCryptogram(byte[] ephemeralPublicKey, byte[] mac, byte[] encryptedData, byte[] nonce,
```
Comment (banterCZ) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java:44]: May we use a builder instead of this telescoping constructor with many parameters of the same type?

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/ByteUtils.java [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+
+import java.nio.ByteBuffer;
+import java.nio.charset.StandardCharsets;
+
+/**
+ * A utility class for handling byte array transformations.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+public class ByteUtils {
```
Comment (banterCZ) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/ByteUtils.java:29]: Util class could be `final` and may hide the constructor.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+import com.google.common.primitives.Bytes;
+
+import java.nio.ByteBuffer;
+
+/**
+ * A utility class for handling ECIES data.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+public class EciesUtils {
```
Comment (banterCZ) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java:28]: dtto

**Review by banterCZ — APPROVED** [review]
Looks good, just minor comments to consider.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java (hunk 1 above)
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java:44]: Yes, we can use a builder.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/ByteUtils.java (hunk 2 above)
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/ByteUtils.java:29]: Good idea.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java (hunk 3 above)
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java:28]: Good idea.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java [hunk 4]
```diff
@@ -28,6 +28,28 @@ public class EciesCryptogram {
     private final byte[] mac;
     private final byte[] encryptedData;
     private final byte[] nonce;
+    private final byte[] associatedData;
+    private final byte[] timestamp;
```
Comment (hvge) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java:32]: I think that it would be better to use `Long` here and do the conversion to bytes internally, if this is the object we fill directly from the request object or use for the response. We can also use Builder, as @banterCZ  suggested, with `Long` at input and keep the bytes in the object.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+     * @param timestampBytes     ECIES request timestamp bytes, required for protocol V3.2+
+     * @param ephemeralKeyPublic Ephemeral public key.
+     * @return Resolved MAC data.
+     */
+    public static byte[] resolveMacData(byte[] sharedInfo2, byte[] encryptedData, byte[] nonce,
+                                        byte[] associatedData, byte[] timestampBytes, byte[] ephemeralKeyPublic) {
+        // Resolve MAC data based on protocol version
+        if (sharedInfo2 == null) {
+            // No shared info, use only encryptedData
+            return encryptedData;
```
Comment (hvge) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java:46]: Is this a special case for encrypting the private token data on V2.1 protocol? If yes, then I think that we can safely remove it and expect that `sharedInfo2` is always available.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+public class EciesUtils {
+
+    /**
+     * Resolve MAC data for ECIES request or response MAC validation.
+     *
+     * @param sharedInfo2        Parameter sharedInfo2 for ECIES.
+     * @param encryptedData      Encypted data.
+     * @param nonce              Nonce, required for protocol V3.1+.
+     * @param associatedData     Data associated with ECIES request or response, required for protocol V3.2+
+     * @param timestampBytes     ECIES request timestamp bytes, required for protocol V3.2+
```
Comment (hvge) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java:37]: I still feel that `Long` is better option for this param :)

**Review by hvge — CHANGES_REQUESTED** [review]
I found some minor issues and one flaw in my design specification that has to be addressed.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java (hunk 5 above)
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java:46]: Yes, I believe this is V2.1 code. I will drop it.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java (hunk 4 above)
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java:32]: Ok, I will switch to `Long`.

**Review by petrdvorak — DISMISSED** [review]
While the intentions of the change are well reasoned and prevent the issue on a system level, I would not write the code 1:1 according to the specification because the resulting protocol seems to diverge from [formal ECIES description](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme#Formal_description_of_ECIES) too much. Instead, I would adjust the code so that:

- core ECIES is unchanged
- additional values (additional data, timestamp, ...) are mapped to SharedInfo1 and SharedInfo2
- EciesCryptogram object is split to "body" (encrypted payload, ephemeral public key, mac) and "headers" (timestamp, nonce, context values such as additional data, etc.)

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java (hunk 1 above)
Comment (banterCZ) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java:47]: Thanks, I see the builder but you still want to keep the public constructor, right?

Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java:47]: Let's not worry about this, because we will refactor this class based on feedback from Petr.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java [hunk 7]
```diff
@@ -212,7 +221,14 @@ private EciesCryptogram encrypt(byte[] data, boolean useIv) throws EciesExceptio
             ivForDecryption = iv;
 
             // Return encrypted payload
-            return new EciesCryptogram(envelopeKey.getEphemeralKeyPublic(), mac, encryptedData, nonce);
+            return EciesCryptogram.builder()
+                    .ephemeralPublicKey(envelopeKey.getEphemeralKeyPublic())
```
[the remark this answers is not in the document]
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java:226]: Ok, I prepared a fix. Feel free to further revise this functionality as required.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java [hunk 8]
```diff
@@ -229,14 +245,17 @@ private EciesCryptogram encrypt(byte[] data, boolean useIv) throws EciesExceptio
      */
     private byte[] decrypt(EciesCryptogram cryptogram) throws EciesException {
         try {
+            // Resolve MAC data based on protocol version
+            final byte[] macData = EciesUtils.resolveMacData(sharedInfo2, cryptogram.getEncryptedData(), cryptogram.getNonce(),
```
[the remark this answers is not in the document]
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java]: The SharedInfo2 generation has been unified.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+     */
+    public static byte[] resolveMacData(byte[] sharedInfo2, byte[] encryptedData, byte[] nonce,
+                                        byte[] associatedData, Long timestamp, byte[] ephemeralKeyPublic) {
+        // Resolve MAC data based on protocol version
+        if (timestamp == null) {
+            // Protocol V3.1 and older
+            return ByteUtils.concat(encryptedData, sharedInfo2);
+        }
+        // Protocol V3.2+
+        final byte[] timestampBytes = ByteBuffer.allocate(8).putLong(timestamp).array();
```
[the remark this answers is not in the document]
Comment (romanstrobl) [reply powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java]: The SharedInfo2 generation has been unified.

**Review by hvge — APPROVED** [review]
Looks OK

**Comment by romanstrobl** [comment]
The updated ECIES implementation is ready for review.

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesPayload.java [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+/**
+ * The EciesPayload structure represents ECIES payload transmitted over the network.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+@Value
+@AllArgsConstructor
+public class EciesPayload {
+
+    EciesCryptogram cryptogram;
```
Comment (banterCZ) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesPayload.java:31]: ~Why is _package private_?~ I see, done by `@Value` https://projectlombok.org/features/Value

File: powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesPayload.java [hunk 11]
```diff
@@ -0,0 +1,60 @@
+/*
+ * PowerAuth Crypto Library
+ * Copyright 2018 Wultra s.r.o.
```
Comment (banterCZ) [inline powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesPayload.java:3]: Is it the class new?

**Review by banterCZ — APPROVED** [review]
Looks good.

**Review by hvge — APPROVED** [review]
Look OK (change about moving `deriveAssociatedData()` to this library)

**Comment by romanstrobl** [comment]
Alright, I will merge this pull request and I will publish the updated powerauth-crypto library after merge
